Detach app service from dev builds
Samagra-Development/PDF-Package pull request #151
Opened 2023-05-31 14:11 UTC by FirePing32

Nest app is now detached from dev builds and needs to be run separately.

fixes:#148

2023-05-31 14:16 UTC, FirePing32 commented
Why is GitGuardian failing ?

2023-06-01 06:06 UTC, FirePing32 commented
Why is GitGuardian failing ?
@yuvrajsab @ChakshuGautam

2023-06-01 06:53 UTC, yuvrajsab commented
@FirePing32, It checks for any secret in the code base since .env.copy file contains a dummy `HASURA_ADMIN_SECRET` secret it is giving this warning. you can ignore this.

2023-06-01 08:01 UTC, yuvrajsab requested changes

2023-06-01 08:01 UTC, yuvrajsab commented on README.md
> +
add a step to run Prisma migrations.
```bash
yarn prisma migrate dev -n init
```

2023-06-01 08:01 UTC, yuvrajsab commented on README.md
add a step here to run migrations in the docker container.
```bash
# go inside the container
docker-compose exec app bash

# run migration
npx prisma migrate dev

# exit out of container
exit
```

2023-06-01 08:01 UTC, yuvrajsab commented on README.md
> +```bash
add a step for creating env file.

2023-06-01 08:01 UTC, yuvrajsab commented on README.md
>  $ docker-compose -f docker-compose.local.yml up -d --build
can remove `--build` flag from here.

2023-06-01 08:16 UTC, FirePing32 commented on README.md
> +```bash
It's a common step for both. That's why it is included at the top, and separate subheadings have been created for development and production.

2023-06-01 08:50 UTC, FirePing32 commented on README.md
Should we instead add these in the Dockerfile ?

2023-06-01 09:22 UTC, yuvrajsab commented on README.md
no, we don't want to run migrations every time we build a new docker image.

2023-06-01 09:23 UTC, yuvrajsab commented on README.md
> +```bash
it's could be confusing, would recommend you add this step to both envs.

2023-06-01 09:44 UTC, yuvrajsab requested changes

2023-06-01 09:44 UTC, yuvrajsab commented on README.md
> +# Copy env file
add a comment something like "You need to edit .env according to your prod setup" ...

2023-06-01 09:44 UTC, yuvrajsab commented on README.md
> +
add pre-requisites here that are node 16, yarn 1, docker and docker-compose.

2023-06-01 09:44 UTC, yuvrajsab commented on README.md
> +
add prerequisites here that are docker and docker-compose.

2023-06-01 10:07 UTC, yuvrajsab approved these changes
LGTM!

2023-06-01 11:11 UTC, FirePing32 commented
@AnshulMalik Please merge.

2023-06-02 05:49 UTC, FirePing32 commented
@yuvrajsab Please merge.

2023-06-02 07:48 UTC, yuvrajsab commented
@AnshulMalik please merge this.

2023-06-04 15:15 UTC, merged